return {
  {
    "formatter-daemon-warmup",
    dir = vim.fn.stdpath "config" .. "/lua/local/formatter-daemon-warmup",
    main = "local.formatter-daemon-warmup",
    event = "VeryLazy",
    opts = {
      delay_ms = 100,
      eslint_d = {
        filetypes = {
          "javascript",
          "javascriptreact",
          "typescript",
          "typescriptreact",
        },
      },
      prettierd = {
        filetypes = {
          "css",
          "graphql",
          "javascript",
          "javascriptreact",
          "json",
          "jsonc",
          "less",
          "markdown",
          "markdown.mdx",
          "mdx",
          "typescript",
          "typescriptreact",
        },
        config_files = {
          ".prettierrc",
          ".prettierrc.json",
          ".prettierrc.yml",
          ".prettierrc.yaml",
          ".prettierrc.json5",
          ".prettierrc.js",
          ".prettierrc.cjs",
          ".prettierrc.mjs",
          ".prettierrc.ts",
          ".prettierrc.cts",
          ".prettierrc.mts",
          ".prettierrc.toml",
          "prettier.config.js",
          "prettier.config.cjs",
          "prettier.config.mjs",
          "prettier.config.ts",
          "prettier.config.cts",
          "prettier.config.mts",
        },
      },
    },
  },
}
